/**
 * MongoDB Seed Script for Geopolitical Intelligence Data
 * This script seeds the MongoDB database with the actual JSON data
 * Run this after setting up MongoDB connection
 */

const data = [
  {
    end_year: "",
    intensity: 6,
    sector: "Energy",
    topic: "gas",
    insight: "Annual Energy Outlook",
    url: "http://www.eia.gov/outlooks/aeo/pdf/0383(2017).pdf",
    region: "Northern America",
    start_year: "",
    impact: "",
    added: "January, 20 2017 03:51:25",
    published: "January, 09 2017 00:00:00",
    country: "United States of America",
    relevance: 2,
    pestle: "Industries",
    source: "EIA",
    title: "U.S. natural gas consumption is expected to increase during much of the projection period.",
    likelihood: 3,
  },
  {
    end_year: "",
    intensity: 6,
    sector: "Energy",
    topic: "oil",
    insight: "Annual Energy Outlook",
    url: "http://www.eia.gov/outlooks/aeo/pdf/0383(2017).pdf",
    region: "Northern America",
    start_year: "",
    impact: "",
    added: "January, 20 2017 03:51:24",
    published: "January, 09 2017 00:00:00",
    country: "United States of America",
    relevance: 2,
    pestle: "Industries",
    source: "EIA",
    title: "Reference case U.S. crude oil production is projected to recover from recent declines.",
    likelihood: 3,
  },
  {
    end_year: "",
    intensity: 6,
    sector: "Energy",
    topic: "consumption",
    insight: "Annual Energy Outlook",
    url: "http://www.eia.gov/outlooks/aeo/pdf/0383(2017).pdf",
    region: "Northern America",
    start_year: "",
    impact: "",
    added: "January, 20 2017 03:51:23",
    published: "January, 09 2017 00:00:00",
    country: "United States of America",
    relevance: 2,
    pestle: "Industries",
    source: "EIA",
    title: "U.S. petroleum consumption is projected to remain below the 2005 level.",
    likelihood: 3,
  },
  {
    end_year: "",
    intensity: 6,
    sector: "Environment",
    topic: "oil",
    insight: "WRI Partnership Aims to Foster Supply Chain Transparency, Zero-Deforestation Strategies",
    url: "http://www.sustainablebrands.com/news_and_views/supply_chain/sustainable_brands/wri_partnership_aims_foster_supply_chain_transparency",
    region: "Central America",
    start_year: "",
    impact: "",
    added: "January, 20 2017 03:26:40",
    published: "January, 18 2017 00:00:00",
    country: "Mexico",
    relevance: 3,
    pestle: "Environmental",
    source: "sustainablebrands.com",
    title:
      "Mars, Unilever, Cargill and Mondelēz are already using GFW Commodities to assess deforestation risks in their palm oil, soy and cocoa supply chains across a collective area of land the size of Mexico.",
    likelihood: 2,
  },
  {
    end_year: 2027,
    intensity: 60,
    sector: "Government",
    topic: "market",
    insight: "E-Boats, Anyone? Electric Boat Market To Reach $20 Billion By 2027, According To New Study",
    url: "https://cleantechnica.com/2017/01/12/e-boats-anyone-electric-boat-market-reach-20b-2027-according-new-study/",
    region: "",
    start_year: "",
    impact: 3,
    added: "January, 18 2017 02:23:13",
    published: "January, 13 2017 00:00:00",
    country: "",
    relevance: 5,
    pestle: "Political",
    source: "CleanTechnica",
    title:
      "The market for non-military electric watercraft and marine motors will balloon to over $20 billion worldwide by 2027.",
    likelihood: 4,
  },
  {
    end_year: 2018,
    intensity: 16,
    sector: "Energy",
    topic: "oil",
    insight: "Oil prices will be much more volatile in 2017",
    url: "http://www.news.tracanada.ca/2017/01/16/oil-prices-will-be-much-more-volatile-in-2017/",
    region: "World",
    start_year: 2017,
    impact: "",
    added: "January, 17 2017 04:19:59",
    published: "January, 16 2017 00:00:00",
    country: "",
    relevance: 4,
    pestle: "Economic",
    source: "TRAC News",
    title:
      "Global oil prices will witness much more volatility in 2017 even though markets may rebalance in the first half of the year if output cuts pledged by producers are implemented.",
    likelihood: 4,
  },
  {
    end_year: 2018,
    intensity: 16,
    sector: "",
    topic: "gdp",
    insight: "IMF affirms Nigeria's recovery from recession, with 0.8% growth forecast",
    url: "http://www.vanguardngr.com/2017/01/imf-affirms-nigerias-recovery-recession-0-8-growth-forecast/",
    region: "Western Africa",
    start_year: 2017,
    impact: "",
    added: "January, 17 2017 03:25:45",
    published: "January, 16 2017 00:00:00",
    country: "Nigeria",
    relevance: 4,
    pestle: "Economic",
    source: "Vanguard News",
    title: "Nigeria Gross Domestic Product will grow by 0.8 percent in 2017 and 2.3 percent in 2018.",
    likelihood: 4,
  },
  {
    end_year: "",
    intensity: 6,
    sector: "Aerospace & defence",
    topic: "war",
    insight: "Lebanon: No Land for Beginning Politicians",
    url: "https://www.avimelamed.com/2017/01/07/lebanon-no-land-for-beginning-politicians/",
    region: "Western Asia",
    start_year: "",
    impact: "",
    added: "January, 17 2017 03:18:22",
    published: "January, 07 2017 00:00:00",
    country: "Lebanon",
    relevance: 2,
    pestle: "Political",
    source: "Avi Melamed",
    title: "A war in Lebanon will increase the already heavy economic burden Saudi Arabia is carrying.",
    likelihood: 3,
  },
  {
    end_year: "",
    intensity: 4,
    sector: "Manufacturing",
    topic: "production",
    insight: "The Slow Road Back: Oil & Gas Industry Outlook for 2017",
    url: "http://deloitte.wsj.com/riskandcompliance/2017/01/10/the-slow-road-back-oil-gas-industry-outlook-for-2017/",
    region: "Northern America",
    start_year: "",
    impact: "",
    added: "January, 17 2017 02:21:11",
    published: "",
    country: "United States of America",
    relevance: 2,
    pestle: "Industries",
    source: "WSJ",
    title: "U.S. production could begin to ramp back up following the rig count upturn.",
    likelihood: 2,
  },
  {
    end_year: "",
    intensity: 6,
    sector: "Retail",
    topic: "export",
    insight: "The Slow Road Back: Oil & Gas Industry Outlook for 2017",
    url: "http://deloitte.wsj.com/riskandcompliance/2017/01/10/the-slow-road-back-oil-gas-industry-outlook-for-2017/",
    region: "Northern America",
    start_year: "",
    impact: "",
    added: "January, 17 2017 02:21:10",
    published: "",
    country: "United States of America",
    relevance: 2,
    pestle: "Economic",
    source: "WSJ",
    title: "More U.S. LNG (liquified natural gas) export capacity is expected to hit the market.",
    likelihood: 3,
  },
  {
    end_year: 2040,
    intensity: 8,
    sector: "Energy",
    topic: "oil",
    insight: "The Peak Oil President?",
    url: "http://www.resilience.org/stories/2017-01-11/the-peak-oil-president/",
    region: "Western Asia",
    start_year: "",
    impact: "",
    added: "January, 16 2017 02:24:59",
    published: "January, 11 2017 00:00:00",
    country: "Saudi Arabia",
    relevance: 4,
    pestle: "Industries",
    source: "Resilience",
    title:
      "By 2040, the world could need to replace over 4 times the current crude oil output of Saudi Arabia (or more than 40 mbd).",
    likelihood: 2,
  },
]

// MongoDB connection and seeding logic
console.log("MongoDB Seed Script - Add Your Connection Logic Here")
console.log(`Total records to seed: ${data.length}`)
console.log("Use this data array to populate your MongoDB collection")
